name: Analysis
on:
  - push
jobs:
  lint:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: psalm
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
          NOVA_USERNAME: ${{secrets.NOVA_USERNAME}}
          NOVA_PASSWORD: ${{secrets.NOVA_PASSWORD}}
        run: |
          composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Psalm
        run: psalm
